### ISSUE TITLE
Error when using `std::span` with cppyy 3.0.0

### ISSUE THREAD

**Issue by marktsuchida** [wlav/cppyy#146]
Given this `test.py`:
```py
import cppyy
cppyy.cppdef("""
#include <span>
std::span<int> my_span;
""")
```

`python test.py` fails with the following error, apparently caused by duplicate definitions in different inline namespaces:
```text
Traceback (most recent call last):
  File "/Users/mark/tmp/cppyy-span-issue/test.py", line 2, in <module>
    cppyy.cppdef("""
  File "/Users/mark/tmp/cppyy-span-issue/venv/lib/python3.10/site-packages/cppyy/__init__.py", line 205, in cppdef
    raise SyntaxError('Failed to parse the given C++ code%s' % err.err)
SyntaxError: Failed to parse the given C++ code
input_line_18:3:6: error: reference to 'span' is ambiguous
std::span<int> my_span;
     ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/span:186:28: note: candidate found by name lookup is 'std::__1::span'
class _LIBCPP_TEMPLATE_VIS span {
                           ^
/private/var/folders/t1/_qv97tt10wj0_zcff4hy0gqc0000gn/T/pip-build-env-02v1l_kq/normal/lib/python3.10/site-packages/cppyy_backend/include/ROOT/span.hxx:155:7: note: candidate found by name lookup is 'std::__CppyyLegacy::span'
class span {
      ^
```

I get the exact same error with `EXTRA_CLING_ARGS` unset or with it set to `-std=c++2a -O2 -march=native`.

(I would have expected no error with `-std=c++2a`, and possibly an error indicating that `span` is not defined otherwise.)

```text
Package       Version
------------- -------
cppyy         3.0.0
cppyy-backend 1.14.11
cppyy-cling   6.28.0
CPyCppyy      1.12.13
pip           23.0.1
setuptools    67.6.0
```

```text
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

```text
Python 3.10.9 (main, Dec 15 2022, 17:11:09) [Clang 14.0.0 (clang-1400.0.29.202)]
```

The same `test.py` runs with no error under cppyy 2:
```text
Package       Version
------------- -------
cppyy         2.4.2
cppyy-backend 1.14.10
cppyy-cling   6.27.1
CPyCppyy      1.12.12
pip           23.0.1
setuptools    67.6.0
```
(Not sure if this is entirely expected either, since `std::span` should not be available in C++17.)

**Comment by wlav** [comment]
Seems that upstream has long time ago added their own `span.hxx` for "compatibility reasons." To pick this added `span.hxx` is conditional on a compile-time configuration variable, which doesn't respond to Cling flags. It also seems to be incorrectly implemented, as it should have figured out that it has `span` in a C++20 build.

I don't think this compatibility version makes much sense for general use, so I think its better to simply remove it.

**Comment by wlav** [comment]
Fixed in repo.

**Comment by agijsberts** [comment]
I confirm that I can wrap code that uses `std::span` now, great!

I still get ambiguity errors when compiling the dictionary for my project though. For the moment I resolved this passing the `R__HAS_STD_SPAN` definition to the compiler (cf. https://github.com/wlav/cppyy-backend/blob/77c19fb685fdf8ac0c657d69a30f73a3f0eda66e/cling/src/core/foundation/inc/ROOT/RSpan.hxx#L19). Is this to be expected or am I missing something?

**Comment by wlav** [comment]
The backend on Linux is still compiled with C++17 for 3.0.0. Will be C++20 on all platforms with 3.0.1. Then I expect `R__HAS_STD_SPAN` to show up as defined in the PCH.

**Comment by wlav** [comment]
Should all be good now with release 3.1.0. Feel free to reopen if you find otherwise.
